name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-22.04
    env:
      CARGO_TOKEN: ${{ secrets.CARGO_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get update
          sudo apt-get install -y libspeechd-dev
          cargo login $CARGO_TOKEN
          rustup toolchain install stable
          cargo publish
