name: Test

on:
  push:
  pull_request:

jobs:
  check_formatting:
    name: Check Formatting
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          rustup toolchain install stable
          cargo fmt --all --check
          cd examples/web
          cargo fmt --all --check

  check:
    name: Check
    strategy:
      matrix:
        os: [windows-latest, ubuntu-22.04, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update; sudo apt-get install -y libspeechd-dev
        if: ${{ runner.os == 'Linux' }}
      - run: |
          rustup toolchain install stable
          cargo clippy --all-targets

  check_web:
    name: Check Web
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          rustup target add wasm32-unknown-unknown
          rustup toolchain install stable
          cargo clippy --all-targets --target wasm32-unknown-unknown

  check_android:
    name: Check Android
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          rustup target add aarch64-linux-android
          rustup toolchain install stable
          cargo clippy --all-targets --target aarch64-linux-android

  check_web_example:
    name: Check Web Example
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          rustup target add wasm32-unknown-unknown
          rustup toolchain install stable
          cd examples/web
          cargo build --target wasm32-unknown-unknown
